import { FastifyReply, FastifyRequest } from "fastify";
import { app } from "../../server";
import { changeUser } from "./changeUser/user";
import { addPlayerToBlockedList, addPlayerToFriendList } from "./userList/addUserList";
import { removeUserInBlockedList, removeUserInFriendsList } from "./userList/removeUserList";
import { putNotification } from "./notify/putNotification";
import { removeNotification } from "./notify/removeNotification";
import { openTournament } from "./tournament/openTournament";
import { joinTournament } from "./tournament/joinTournament";
import { quitTournament } from "./tournament/quitTournament";
import { findPlayer } from "./findPlayer/findPlayer";
import { createAccount } from "./connexion/createAccount";
import { connexionAccount } from "./connexion/connexionAccount";
import { getDataPlayer } from "./getDataPlayer/getDataPlayer";
import { takeOffNotification } from "./notify/takeOffNotification";
import { createGame } from "./game/createGame";
import { quitQueue } from "./game/quitQueue";
import { acceptMatch } from "./game/acceptMatch";
import { tryToConnect } from "./connexion/tryToConnect";
import { authentication } from "../authentication/authentication";
import { verifyCode } from "./connexion/code";
import { changeEmail } from "./changeUser/email";
import { changePassword } from "./changeUser/password";
import { verifyEmail } from "./changeUser/verify";
import { deleteAccount } from "./changeUser/delete";
import { deleteAccountVerify } from "./changeUser/deleteVerify";
import { movePaddle } from "./game/paddle/move";
import { stopPaddle } from "./game/paddle/stop";
import { giveFront } from "./connexion/giveFront";
import { disconnect } from "./connexion/disconnect";

export function routes() {
    app.get("/", giveFront);
    app.get("/connect", tryToConnect);
    app.get("/api/login", connexionAccount);
    app.post("/api/signin", createAccount);
    app.get("/api/verify", verifyCode);
    
    app.delete("/api/disconnect", { preHandler: authentication }, disconnect);
    app.put("/api/settings/volume/general", { preHandler: authentication}, changeUser);
    app.put("/api/settings/volume/noises", { preHandler: authentication}, changeUser);
    app.put("/api/settings/volume/music", { preHandler: authentication}, changeUser);
    app.put("/api/settings/key/player1/up", { preHandler: authentication}, changeUser);
    app.put("/api/settings/key/player1/down", { preHandler: authentication}, changeUser);
    app.put("/api/settings/key/player2/up", { preHandler: authentication}, changeUser);
    app.put("/api/settings/key/player2/down", { preHandler: authentication}, changeUser);
    app.put("/api/settings/account/email", { preHandler: authentication}, changeEmail);
    app.put("/api/settings/account/password", { preHandler: authentication}, changePassword);
    app.put("/api/settings/account/pseudo", { preHandler: authentication}, changeUser);
    app.put("/api/settings/account/verify", { preHandler: authentication}, verifyEmail);
    app.put("/api/settings/language", { preHandler: authentication}, changeUser);
    app.delete("/api/settings/delete", { preHandler: authentication}, deleteAccount);
    app.delete("/api/settings/delete/verify", { preHandler: authentication}, deleteAccountVerify);
    app.put("/api/mode", { preHandler: authentication}, changeUser);
    app.put("/api/profile/picture", { preHandler: authentication}, changeUser);
    app.post("/api/profile/friends/add", { preHandler: authentication}, addPlayerToFriendList);
    app.post("/api/profile/blocked/add", { preHandler: authentication}, addPlayerToBlockedList);
    app.delete("/api/profile/friends/remove", { preHandler: authentication}, removeUserInFriendsList);
    app.delete("/api/profile/blocked/remove", { preHandler: authentication}, removeUserInBlockedList);
    app.post("/api/profile/notify/put", { preHandler: authentication}, putNotification);
    app.delete("/api/profile/notify/remove", { preHandler: authentication}, removeNotification);
    app.delete("/api/profile/notify/takeoff", { preHandler: authentication}, takeOffNotification);
    app.get("/api/profile/search", { preHandler: authentication}, findPlayer);
    app.post("/api/mode/tournament/open", { preHandler: authentication}, openTournament);
    app.put("/api/mode/tournament/join", { preHandler: authentication}, joinTournament);
    app.put("/api/mode/tournament/quit", { preHandler: authentication}, quitTournament);
    app.get("/api/player", { preHandler: authentication}, getDataPlayer);
    app.post("/api/game/search", { preHandler: authentication}, createGame);
    app.delete("/api/game/quit", { preHandler: authentication}, quitQueue);
    app.post("/api/game/accept", { preHandler: authentication}, acceptMatch);
    app.post("/api/game/move", { preHandler: authentication}, movePaddle);
    app.post("/api/game/stop", { preHandler: authentication}, stopPaddle);
}
